### ISSUE TITLE
Error about satacprocess function in SCATE

### ISSUE THREAD

**Issue by xxihe** [zji90/SCATE#1]
Hi,
I followed the R codes in the user manual PDF file. I got the error about the parameter 'libsizefilter' in the function satacprocess. I don't whether to keep it or not, since both situations led to errors. I have already installed the latest version of SCATE. Do you know how to fix it?

<img width="849" alt="Screen Shot 2020-09-22 at 10 02 52 AM" src="https://user-images.githubusercontent.com/43379286/93892677-c9530800-fcba-11ea-9630-9e9500c4b1e6.png">

Best,
Xi

**Comment by zji90** [comment]
Hi Xi,
Sorry, there is a typo in this function. I have fixed the typo. Please update the package and try it out again. Thanks!
