### ISSUE TITLE
2 alignments are not on the same chromosome

### ISSUE THREAD

**Issue by YOU-k** [zji90/SCATE#2]
Hi, 
I used SCATE to process bam file delivered by Cell Ranger, with 
`satac <- satacprocess(input=bamlist,type='bam',libsizefilter=1000)`,
However I got 
Error in .local(x, use.names, use.mcols, ...) : 
  For some pairs in 'x', the 2 alignments are not on the same chromosome.
  Cannot associate a unique genomic range to such pairs. Please call
  granges() with 'on.discordant.seqnames="drop"' to drop these pairs, or
  with 'on.discordant.seqnames="split"' to represent each of them with 2
  genomic ranges in the returned GRanges object. Note that in both cases
  the returned object won't be parallel to 'x'. Alternatively, please
  consider using grglist() instead of granges() to turn 'x' into a
  GRangesList object instead of a GRanges object. See ?GAlignmentPairs
  for more information.
What should I do?  Thanks for your suggestions.

**Comment by zji90** [comment]
Hi,
I have made a fix to 'satacprocess' by adding the argument of 'on.discordant.seqnames="drop"'. Please redownload the package and try. Let me know if it works now. Thanks!

**Comment by YOU-k** [comment]
I redownload it, but i was told that unused argument (on.discordant.seqnames = "drop").
if i still use `satac <- satacprocess(input=bamlist,type='bam',libsizefilter=1000)`
there returns the same error. is there any suggestion?

**Comment by zji90** [comment]
OK. Is it possible to send over the raw data that triggers the problem and I can take a look?
Another possibility is to read in the data by your own into GRanges object in R and call the analysis downstream of satacprocess.

**Comment by SidG13** [comment]
Not sure if you already got a solution to this, but I had the same problem. Was fixed by running lines from the source code:
```R
bams_as_Granges <- sapply(sapply(bamlist, readGAlignmentPairs), granges, on.discordant.seqnames = "drop")
satac <- satacprocess(input=bams_as_Granges, type='gr', libsizefilter = 1000, pairsingle = "paired")
```

**Comment by zji90** [comment]
Thanks. on.discordant.seqnames = "drop" should do the trick.
