### ISSUE TITLE
what is the official repository?

### ISSUE THREAD

**Issue by nsheff** [zji90/SCATE#3]
can you clarify the relationship of this repository to https://github.com/Winnie09/SCATE ?

**Comment by zji90** [comment]
Hi,
https://github.com/Winnie09/SCATE is a clone of this repo mainly used for Bioconductor submission and will no longer be updated in the future. All future updates will be made in this repo (https://github.com/zji90/SCATE).

**Comment by nsheff** [comment]
Ok... Do you mean you are not planning to push future updates into bioconductor? Because the history in this repository will be incongruent with bioconductor's git server, right?

Also the other repository has one key advantage that it does not have 100Mb of data inside the git repo here: https://github.com/zji90/SCATE/tree/master/inst/extdata -- which for me at least makes it kind of a non-starter to clone this repository...

**Comment by zji90** [comment]
The repo in Bioconductor and (https://github.com/Winnie09/SCATE) are different from this repo. The difference is mainly to meet the requirements from Bioconductor, for example, the data is separated into another folder. 

All updates will be made in this repo and the Bioconductor version will be updated less frequently (it is hard to maintain two different versions simultaneously).

Thanks!
